package com.example.habitualize.utils

const val isFirstTimeOpenApp = "is_first_time_open_app"
const val languageCode = "language_code"
const val isLanguageScreenShow = "is_language_screen_show"
const val isLogIn = "is_login"
const val userName = "user_name"
const val userImage = "user_image"
const val userCoins = "user_coins"
const val userId = "user_id"
const val gratitudeReward1 = "gratitude_reward_1"
const val gratitudeReward2 = "gratitude_reward_2"
const val gratitudeRevealDate = "gratitude_reveal_date"
const val isAppTasksLocal = "is_app_tasks_local"

//reward strings
const val openAppCounter = "open_app_counter"
const val openAppCounterForRateUs = "open_app_counter_for_rate_us"
const val openTaskCounter = "open_counter"
const val completeTaskCounter = "task_counter"
const val addTaskCounter = "add_task_counter"
const val addCommunityChallengeCounter = "add_community_challenge_counter"
const val shareAppCounter = "share_app_counter"
const val purchaseThemeCounter = "purchase_theme_counter"
const val gratitudeScratchCounter = "gratitude_scratch_counter"
const val selectedColorIndex = "selected_color_index"
const val isBlogDialogShowed = "is_blog_dialog_showed"
const val isNotificationAllow = "is_notification_allow"
const val noCoinMsg = "Not Enough Coins"